spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote
    #url: jdbc:mysql://localhost:3306/springbatch26
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8089
